package prefill

import (
	"math"
	"testing"
	"time"
)

// A line recovered from points generated by a known velocity is the whole
// claim: if Fit cannot get 1/A back, nothing downstream can size a fleet.
func TestFitRecoversTheTokenVelocity(t *testing.T) {
	const velocity = 140000.0 // prompt tokens/s, the order run PK measured
	const fixed = 0.05        // seconds

	var obs []Observation
	for tok := 1000.0; tok <= 60000; tok += 5000 {
		obs = append(obs, Observation{
			Tokens:  tok,
			TTFTSec: tok/velocity + fixed,
			At:      time.Now(),
		})
	}

	m, ok := Fit(obs)
	if !ok {
		t.Fatalf("Fit declined a clean line")
	}
	if got := m.TokenVelocity(); math.Abs(got-velocity)/velocity > 1e-6 {
		t.Errorf("TokenVelocity = %.1f, want %.1f", got, velocity)
	}
	if math.Abs(m.B-fixed) > 1e-6 {
		t.Errorf("B = %.6f, want %.6f", m.B, fixed)
	}
}

func TestFitRejects(t *testing.T) {
	now := time.Now()
	cases := []struct {
		name string
		obs  []Observation
	}{
		{
			// The ordinary case a steady fleet produces, and the one that
			// would otherwise divide by zero.
			name: "no spread in the regressor",
			obs: []Observation{
				{Tokens: 30000, TTFTSec: 0.3, At: now},
				{Tokens: 30000, TTFTSec: 0.4, At: now},
				{Tokens: 30000, TTFTSec: 0.5, At: now},
			},
		},
		{
			// More tokens costing less time is not a prefill replica.
			name: "inverted slope",
			obs: []Observation{
				{Tokens: 1000, TTFTSec: 1.0, At: now},
				{Tokens: 50000, TTFTSec: 0.1, At: now},
			},
		},
		{
			name: "too few points",
			obs:  []Observation{{Tokens: 1000, TTFTSec: 0.1, At: now}},
		},
		{
			// A flat line implies an infinite velocity; the fleet would be
			// sized at one replica for any load.
			name: "flat",
			obs: []Observation{
				{Tokens: 1000, TTFTSec: 0.5, At: now},
				{Tokens: 50000, TTFTSec: 0.5, At: now},
			},
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if m, ok := Fit(tc.obs); ok {
				t.Errorf("Fit accepted %s: A=%g B=%g velocity=%g", tc.name, m.A, m.B, m.TokenVelocity())
			}
		})
	}
}

// TokenVelocity must fail closed. A caller that skips IsZero gets a figure
// that fails `> 0`, not an infinity that sizes a fleet.
func TestTokenVelocityOfAnInvalidModelIsZero(t *testing.T) {
	for _, m := range []Model{
		{},
		{A: 0, B: 0.1},
		{A: -1e-3, B: 0.1},
		{A: math.NaN(), B: 0.1},
		{A: 1e-12, B: 0.1}, // a velocity of 1e12 tokens/s
	} {
		if v := m.TokenVelocity(); v != 0 {
			t.Errorf("TokenVelocity(%+v) = %g, want 0", m, v)
		}
	}
}

func TestWindowAddRejectsUninformativeObservations(t *testing.T) {
	w := NewWindow(10)
	now := time.Now()
	for _, o := range []Observation{
		{Tokens: 30000, TTFTSec: 0, At: now},           // no latency
		{Tokens: 30000, TTFTSec: -1, At: now},          // negative
		{Tokens: 10, TTFTSec: 0.5, At: now},            // below the backlog floor
		{Tokens: math.NaN(), TTFTSec: 0.5, At: now},    // NaN regressor
		{Tokens: 30000, TTFTSec: math.Inf(1), At: now}, // infinite latency
	} {
		if w.Add(o) {
			t.Errorf("Add accepted %+v", o)
		}
	}
	if w.Len() != 0 {
		t.Errorf("window holds %d, want 0", w.Len())
	}
	if !w.Add(Observation{Tokens: 30000, TTFTSec: 0.3, At: now}) {
		t.Error("Add rejected a good observation")
	}
}

func TestWindowReadyNeedsSpread(t *testing.T) {
	w := NewWindow(20)
	now := time.Now()
	// Ten points, all at the same backlog: enough samples, no spread.
	for i := 0; i < 10; i++ {
		w.Add(Observation{Tokens: 30000, TTFTSec: 0.3, At: now})
	}
	if w.Ready(DefaultMinSamples, DefaultMinTokenSpread) {
		t.Error("Ready with no spread in the regressor")
	}
	w.Add(Observation{Tokens: 1000, TTFTSec: 0.1, At: now})
	if !w.Ready(DefaultMinSamples, DefaultMinTokenSpread) {
		t.Error("not Ready once the regressor spread")
	}
}

func TestWindowPruneDropsStale(t *testing.T) {
	w := NewWindow(20)
	now := time.Now()
	w.Add(Observation{Tokens: 30000, TTFTSec: 0.3, At: now.Add(-time.Hour)})
	w.Add(Observation{Tokens: 30000, TTFTSec: 0.3, At: now})
	w.Prune(now, DefaultObservationMaxAge)
	if w.Len() != 1 {
		t.Errorf("after Prune window holds %d, want 1", w.Len())
	}
}

func TestWindowEvictsOldestWhenFull(t *testing.T) {
	w := NewWindow(3)
	now := time.Now()
	for i := 1; i <= 5; i++ {
		w.Add(Observation{Tokens: float64(1000 * i), TTFTSec: 0.1, At: now})
	}
	if w.Len() != 3 {
		t.Fatalf("window holds %d, want 3", w.Len())
	}
	if got := w.Observations()[0].Tokens; got != 3000 {
		t.Errorf("oldest kept is %v, want 3000", got)
	}
}
